Add user-agent to the request header
aliyun/alibabacloud-api-vscode-toolkit pull request #79
Opened 2024-06-11 09:15 UTC by yini-chen

1. Add user-agent to the request header;
2. Fixed UI problem.

2024-06-11 15:05 UTC, JacksonTian requested changes

2024-06-11 15:05 UTC, JacksonTian commented on src/Service.ts
> +        "User-Agent": `Toolkit (${os.type()}; ${os.release()}) alibababcloud-api-toolkit/${vscode.extensions.getExtension("alibabacloud-openapi.vscode-alicloud-api").packageJSON.version} VS Code/${vs
可以放个 helper 方法 getUserAgent()。这样方便测试，后续改动也容易维护。

2024-06-12 08:20 UTC, yini-chen commented on src/Service.ts
> +        "User-Agent": `Toolkit (${os.type()}; ${os.release()}) alibababcloud-api-toolkit/${vscode.extensions.getExtension("alibabacloud-openapi.vscode-alicloud-api").packageJSON.version} VS Code/${vs
resolved

2024-06-13 03:31 UTC, jasonHzq reviewed
LGTM

2024-06-13 03:31 UTC, jasonHzq approved these changes
LGTM

2024-06-13 03:39 UTC, JacksonTian approved these changes

2024-06-13 03:43 UTC, merged